---
title: Islamic Center Of San Diego
timezone: UTC
collections:
  about-us:
    title: About Us
    output: true
    permalink: "/:collection/:title"
  announcements:
    title: Announcements
    output: true
    permalink: "/:collection/:title"
  applications:
    title: Applications
    output: true
    permalink: "/:collection/:title"
  classifieds:
    title: Classifieds
    output: true
    permalink: "/:collection/:title"
  events:
    title: Events
    output: true
    permalink: "/:collection/:title"
  islam:
    title: Islam
    output: true
    permalink: "/:collection/:title"
  media:
    title: Media
    output: true
    permalink: "/:collection/:title"
  nav-pages:
    title: Nav Pages
    output: true
    permalink: "/:title"
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
    permalink: "/:collection/:title"
  sliders:
    title: Sliders
    output: false
    target-window: blank
  uploads:
    title: Uploads
    output: true
  youth:
    title: Youth
    output: true
    permalink: "/:collection/:title"
email: webmaster@icsd.org
description: Build Strong Commmunities.
baseurl: '/icsd.org'
url: https://webmaster-icsd.github.io
twitter_username: IslamicCenterSD
github_username: webmaster.icsd
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
prose:
  rooturl: ''
  siteurl: https://webmaster-icsd.github.io/icsd.org/
  media: media
  relativeLinks: https://webmaster-icsd.github.io/icsd.org/links.jsonp
  ignore:
  - index.md
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/_scss"
  - "/_sass"
  - "/css"
  - "/icsd_collections"
  - "/js"
  metadata:
    _services:
    - name: layout
      field:
        label: Layout
        value: page-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Choose Tags
        options:
        - name: Apples
          value: apples
        - name: Bananas
          value: bananas
    _nav-pages:
    - name: layout
      field:
        label: Layout
        value: page-with-sidebar-layout
        element: select
        placeholder: Choose Tags
        options:
        - name: Page with sidebar
          value: page-with-sidebar-layout
        - name: Page with full width
          value: page-with-full-width-layout
    - name: title
      field:
        label: Title
        element: text
    _nav-pages/prayer-times:
    - name: fajr
      field:
        label: Fajr
        value: '00:00'
        element: text
    - name: title
      field:
        label: Title
        element: text
    _applications:
    - name: layout
      field:
        label: Layout
        value: page-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Choose Tags
        options:
        - name: Apples
          value: apples
        - name: Bananas
          value: bananas
    _about-us:
    - name: layout
      field:
        label: Layout
        value: page-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Choose Tags
        options:
        - name: Apples
          value: apples
        - name: Bananas
          value: bananas
    _media:
    - name: layout
      field:
        label: Layout
        value: page-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: tags
      field:
        element: multiselect
        label: Add Tags
        placeholder: Choose Tags
        options:
        - name: Apples
          value: apples
        - name: Bananas
          value: bananas
    _classifieds:
    - name: layout
      field:
        label: Layout
        value: collection-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: expiration-date
      field:
        label: Expiration Date
        element: text
        value: CURRENT_DATETIME
        type: date
    - name: collection-name
      field:
        element: text
        value: classifieds
    _events:
    - name: event-date
      field:
        label: Event Date
        element: text
        value: CURRENT_DATETIME
    - name: layout
      field:
        label: Layout
        value: collection-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: collection-name
      field:
        element: text
        value: events
    _islam:
    - name: layout
      field:
        label: Layout
        value: collection-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: collection-name
      field:
        element: text
        value: islam
    _announcements:
    - name: layout
      field:
        label: Layout
        value: collection-with-sidebar-layout
        element: text
    - name: title
      field:
        label: Title
        element: text
    - name: collection-name
      field:
        element: text
        value: annoucements
    _sliders:
    - name: title
      field: 
      label: Title
      element: text
    - name: image-url
      field:
        label: Background Image
        value: images/icsd-musallah.jpg
        element: text
    - name: target-url
      field:
        label: Target Url
        element: text
    - name: expire
      field:
        label: Expire
        element: checkbox
        value: false
    - name: expiration-date
      field:
        label: Expiration Date
        help: Expiration Date will be considered only if Expire checkbox is clecked.
        element: text
        value: CURRENT_DATETIME
